export const demoGenres = [
  {
    id: '1',
    name: 'Fiction',
    children: [
      { id: '1-1', name: 'Fantasy' },
      { id: '1-2', name: 'Mystery' },
      { id: '1-3', name: 'Classic' },
    ],
  },
  {
    id: '2',
    name: 'Non-Fiction',
    children: [
      { id: '2-1', name: 'History' },
      { id: '2-2', name: 'Science' },
    ],
  },
  {
    id: '3',
    name: 'Personal Growth',
    children: [
      { id: '3-1', name: 'Self-help' },
      { id: '3-2', name: 'Productivity' },
    ],
  },
];

export const demoBooks = [
  {
    id: '101',
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    isbn: '9780141321083',
    description: 'A heartwarming tale of friendship, renewal, and the magic of a hidden garden.',
    genre: { id: '1-1', name: 'Fantasy' },
    genreId: '1-1',
    genreName: 'Fantasy',
    availableCopies: 4,
    totalCopies: 5,
    publisher: 'Penguin Classics',
    publicationDate: '1911-08-01',
    createdAt: '2024-06-01T09:00:00Z',
  },
  {
    id: '102',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    isbn: '9780525559474',
    description: 'A reflective novel about choice, regret, and the many possible lives you could live.',
    genre: { id: '1-2', name: 'Mystery' },
    genreId: '1-2',
    genreName: 'Mystery',
    availableCopies: 0,
    totalCopies: 4,
    publisher: 'Viking',
    publicationDate: '2020-09-29',
    createdAt: '2024-06-03T10:15:00Z',
  },
  {
    id: '103',
    title: 'The Power of Habit',
    author: 'Charles Duhigg',
    isbn: '9780812981605',
    description: 'A clear guide to how habits work and how to build new ones for lasting change.',
    genre: { id: '3-1', name: 'Self-help' },
    genreId: '3-1',
    genreName: 'Self-help',
    availableCopies: 5,
    totalCopies: 5,
    publisher: 'Random House',
    publicationDate: '2012-02-28',
    createdAt: '2024-06-05T13:25:00Z',
  },
  {
    id: '104',
    title: 'Cosmos',
    author: 'Carl Sagan',
    isbn: '9780345539434',
    description: 'An inspiring exploration of the universe and humanity’s place within it.',
    genre: { id: '2-2', name: 'Science' },
    genreId: '2-2',
    genreName: 'Science',
    availableCopies: 1,
    totalCopies: 2,
    publisher: 'Ballantine Books',
    publicationDate: '1980-10-12',
    createdAt: '2024-05-28T08:45:00Z',
  },
  {
    id: '105',
    title: 'The Art of War',
    author: 'Sun Tzu',
    isbn: '9781590302255',
    description: 'A classic strategic manual that explores leadership, planning, and disciplined action.',
    genre: { id: '2-1', name: 'History' },
    genreId: '2-1',
    genreName: 'History',
    availableCopies: 2,
    totalCopies: 3,
    publisher: 'Shambhala',
    publicationDate: '500-01-01',
    createdAt: '2024-05-30T11:05:00Z',
  },
];

export const demoBookLoans = [
  {
    id: 'loan-101',
    bookId: '101',
    bookTitle: 'The Secret Garden',
    bookAuthor: 'Frances Hodgson Burnett',
    bookIsbn: '9780141321083',
    checkoutDate: '2024-06-03T10:00:00Z',
    dueDate: '2024-06-24T10:00:00Z',
    status: 'CHECKED_OUT',
    fineAmount: 0,
    finePaid: true,
    overdueDays: 0,
    renewalCount: 1,
    maxRenewals: 2,
    isOverdue: false,
    returnDate: null,
    notes: 'Reading for the summer book club.',
  },
  {
    id: 'loan-102',
    bookId: '102',
    bookTitle: 'The Midnight Library',
    bookAuthor: 'Matt Haig',
    bookIsbn: '9780525559474',
    checkoutDate: '2024-05-20T15:30:00Z',
    dueDate: '2024-06-05T15:30:00Z',
    status: 'OVERDUE',
    fineAmount: 18.0,
    finePaid: false,
    overdueDays: 7,
    renewalCount: 0,
    maxRenewals: 2,
    isOverdue: true,
    returnDate: null,
    notes: 'Please pay the overdue fine before renewing.',
  },
  {
    id: 'loan-103',
    bookId: '103',
    bookTitle: 'The Power of Habit',
    bookAuthor: 'Charles Duhigg',
    bookIsbn: '9780812981605',
    checkoutDate: '2024-04-05T09:15:00Z',
    dueDate: '2024-04-19T09:15:00Z',
    status: 'RETURNED',
    fineAmount: 0,
    finePaid: true,
    overdueDays: 0,
    renewalCount: 0,
    maxRenewals: 2,
    isOverdue: false,
    returnDate: '2024-04-18T11:00:00Z',
    notes: 'Great read on how small habits make a big difference.',
  },
  {
    id: 'loan-104',
    bookId: '104',
    bookTitle: 'Cosmos',
    bookAuthor: 'Carl Sagan',
    bookIsbn: '9780345539434',
    checkoutDate: '2024-06-06T14:20:00Z',
    dueDate: '2024-06-20T14:20:00Z',
    status: 'CHECKED_OUT',
    fineAmount: 0,
    finePaid: true,
    overdueDays: 0,
    renewalCount: 0,
    maxRenewals: 1,
    isOverdue: false,
    returnDate: null,
    notes: null,
  },
];
